version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      API_BASE: "/api"
      GCP_PROJECT_ID: "local-dev"   # за mock; реалните BQ заявки може да са изключени локално
      BQ_DATASET: "ai_health"
      ETL_BEARER: "local-strong-bearer"
      GEMINI_API_KEY: "mock-gemini"
  connector:
    build: ./connector
    ports:
      - "8080:8080"
    environment:
      PORT: "8080"
    depends_on:
      - backend