

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[build]
  command = "cd frontend && npm ci && npx ng build --configuration production"
  publish = "frontend/dist/frontend/browser"

[[redirects]]
  from = "/api/ask"
  to = "/.netlify/functions/ask"
  status = 200
  force = true

[[redirects]]
  from = "/api/search"
  to = "/.netlify/functions/search"
  status = 200
  force = true

[[redirects]]
  from = "/api/analytics/snapshot"
  to = "/.netlify/functions/analytics-snapshot"
  status = 200
  force = true

[[redirects]]
  from = "/etl/events"
  to = "/.netlify/functions/etl-events"
  status = 200
  force = true

[[redirects]]
  from = "/etl/health"
  to = "/.netlify/functions/etl-health"
  status = 200
  force = true
