[build]
  command = "cd frontend && npm ci && npx ng build --configuration production"
  publish = "frontend/dist/frontend/browser"

[[redirects]]
  from = "/api/*"
  to = "https://YOUR-ACTUAL-BACKEND-URL/:splat"
  status = 200
  force = true