
  [build]
  command = "cd frontend && npm ci && npx ng build --configuration production"
  publish = "frontend/dist/frontend/browser"

[[redirects]]
  from = "/api/*"
  to = "https://ai-health-backend-473242551252.europe-west1.run.app/api/:splat"
  status = 200
  force = true
