

[build]
  command = "cd frontend && npm ci && npx ng build --configuration production"
  publish = "frontend/dist/frontend/browser"

[[redirects]]
  from = "/api/ask"
  to = "/.netlify/functions/ask"
  status = 200
  force = true
