[build]
  base = "frontend"
  command = "npm install && npx ng build --configuration production"
  publish = "dist/frontend"

[[redirects]]
  from = "/api/*"
  to = "https://<BACKEND_CLOUD_RUN_URL>/:splat"
  status = 200
  force = true