

[build]
  command = "cd frontend && npm ci && npx ng build --configuration production"
  publish = "frontend/dist/frontend/browser"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
