[build]
  command = "ng build --configuration production"
  publish = "dist/ai-health-frontend/browser"

[[redirects]]
  from = "/api/*"
  to = "https://<BACKEND_CLOUD_RUN_URL>/:splat"
  status = 200
  force = true