

[build]
  command = "cd frontend && npm ci && npx ng build --configuration production"
  publish = "frontend/dist/frontend/browser"

[[redirects]]
  from = "/api/*"
  to = "https://YOUR-RENDER-APP-NAME.onrender.com/api/:splat"
  status = 200
  force = true
