services:
  - type: web
    name: ai-health-backend
    env: node
    buildCommand: npm ci
    startCommand: node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001